/**
 * Initial Seed Data for Digital Village
 * Contains rich real-world data for all 16 facilities, 6 projects, 6 festivals,
 * upcoming events, 20 gallery items, places, heroes, news, and village profile.
 */

export const initialVillageData = {
  name: 'Sundarpur',
  hindiName: 'सुंदरपुर डिजिटल ग्राम पंचायत',
  tagline: 'Our Village, Our Culture, Our Pride 🌾',
  state: 'Uttar Pradesh',
  district: 'Varanasi',
  block: 'Kashi Vidyapeeth',
  pincode: '221001',
  establishedYear: 1842,
  description:
    'Sundarpur is an award-winning model Digital Smart Gram Panchayat. Nestled amidst lush green agricultural landscapes along sacred river tributaries, our village represents the perfect harmony of rich Indian cultural heritage, Vedic values, and state-of-the-art 21st-century digital empowerment.',
  history:
    'Established in 1842 by agricultural craftsmen and trade artisans, Sundarpur was renowned for its fertile mango groves, heritage stepwells, and ancient Shiva temple. Over generations, the community united under selfless rural leaders. In 2023, Sundarpur was officially designated a 100% Solar Powered & Fiber-Connected Digital Gram Panchayat, providing transparent e-governance, digital healthcare, and smart education to every resident.',
  statistics: {
    population: 5420,
    houses: 1180,
    schools: 4,
    roadsKm: 28,
    greenAreaPercent: 78,
    waterSources: 14,
  },
  panchayatInfo: {
    sarpanch: 'Mukhiya Rajesh Kumar Verma',
    upSarpanch: 'Smt. Kaushalya Devi',
    secretary: 'Shri Anil Kumar Singh',
    wardMembersCount: 12,
    helpline: '+91 98765 43210',
    officeEmail: 'panchayat@sundarpur-village.in',
    officeHours: 'Mon - Sat: 9:00 AM - 5:00 PM',
    officeLocation: 'Ward No. 04, Panchayat Bhawan, Main Road, Sundarpur',
  },
  emergencyContacts: {
    police: '112 / +91 94544 00100 (Kotwali Outpost)',
    ambulance: '108 / 102 (24/7 Rural Emergency Response)',
    fire: '101',
    electricityBoard: '1912 / +91 94150 12345 (Junior Engineer)',
    womenHelpline: '1090',
    kisanCallCenter: '1800-180-1551 (Toll-Free Agricultural Advice)',
  },
};

export const initialFacilities = [
  {
    id: 'fac-1',
    order: 1,
    title: 'Education',
    icon: 'fa-solid fa-graduation-cap',
    category: 'Essential',
    description: 'Smart digital classrooms, high school, girls secondary school, and a public e-library with free internet.',
    details: 'Equipped with 4 schools, 32 teachers, STEM computer lab, and mid-day meal nutritional program.',
    isAvailable: true,
    timings: '8:00 AM - 3:00 PM',
  },
  {
    id: 'fac-2',
    order: 2,
    title: 'Healthcare',
    icon: 'fa-solid fa-hospital',
    category: 'Essential',
    description: '24/7 Primary Health Centre (PHC) with MBBS doctor, dedicated maternity ward, and telemedicine center.',
    details: 'Free diagnostic medicines, weekly maternal checkups, and ambulance on call.',
    isAvailable: true,
    timings: '24 Hours Emergency / 9 AM - 4 PM OPD',
  },
  {
    id: 'fac-3',
    order: 3,
    title: 'Drinking Water',
    icon: 'fa-solid fa-faucet-drip',
    category: 'Utility',
    description: 'Har Ghar Nal Se Jal initiative delivering purified RO tap water to 1,180 households twice daily.',
    details: 'Solar-powered dual water treatment plants with automated water purity sensor monitors.',
    isAvailable: true,
    timings: '6:00 AM - 10:00 AM & 5:00 PM - 8:00 PM',
  },
  {
    id: 'fac-4',
    order: 4,
    title: 'Electricity',
    icon: 'fa-solid fa-bolt',
    category: 'Utility',
    description: '24/7 uninterrupted power supply backed by a 250 kW village community solar microgrid.',
    details: 'Zero load-shedding during agricultural peak hours with prepaid digital smart metering.',
    isAvailable: true,
    timings: '24/7 Uninterrupted',
  },
  {
    id: 'fac-5',
    order: 5,
    title: 'Roads',
    icon: 'fa-solid fa-road',
    category: 'Infrastructure',
    description: 'All-weather PMGSY concrete paved main arterial roads connecting every hamlet and farm to the highway.',
    details: '28 km engineered concrete roads with covered storm rainwater drainage systems on both sides.',
    isAvailable: true,
    timings: 'All Seasons Passable',
  },
  {
    id: 'fac-6',
    order: 6,
    title: 'Internet',
    icon: 'fa-solid fa-wifi',
    category: 'Digital',
    description: 'BharatNet gigabit optical fiber network with free Wi-Fi hotspots across Panchayat Bhawan, market & schools.',
    details: '100 Mbps fiber line with public digital literacy kiosk for online certificates and forms.',
    isAvailable: true,
    timings: '24/7 High-Speed Access',
  },
  {
    id: 'fac-7',
    order: 7,
    title: 'Local Market',
    icon: 'fa-solid fa-store',
    category: 'Commerce',
    description: 'Bustling daily farmers Haat Bazaar with organic produce, fresh dairy, handicraft stalls, and UPI payments.',
    details: '50+ permanent stalls, cold vegetable storage counter, and direct farmer-to-consumer pricing.',
    isAvailable: true,
    timings: '6:30 AM - 1:00 PM & 4:00 PM - 9:00 PM',
  },
  {
    id: 'fac-8',
    order: 8,
    title: 'Temple',
    icon: 'fa-solid fa-place-of-worship',
    category: 'Cultural',
    description: 'Centuries-old Shri Someshwar Mahadev Temple and sacred stepwell pond serving as spiritual heart of village.',
    details: 'Daily Vedic Aarti, peaceful community meditation courtyard, and annual festival gatherings.',
    isAvailable: true,
    timings: '5:00 AM - 12:00 PM & 4:30 PM - 9:00 PM',
  },
  {
    id: 'fac-9',
    order: 9,
    title: 'Gram Panchayat',
    icon: 'fa-solid fa-building-columns',
    category: 'Governance',
    description: 'Air-conditioned digital Panchayat Secretariat providing e-GramSwaraj public citizen services under one roof.',
    details: 'Instant caste, income, birth/death certificate processing and bi-weekly open Gram Sabha public hearings.',
    isAvailable: true,
    timings: '10:00 AM - 5:00 PM (Monday to Saturday)',
  },
  {
    id: 'fac-10',
    order: 10,
    title: 'Transportation',
    icon: 'fa-solid fa-bus-simple',
    category: 'Mobility',
    description: 'Regular electric mini-bus service connecting the village bus terminal to the district railway station and hospital.',
    details: 'Every 30 minutes shared e-rickshaws and state transport bus halts at main square.',
    isAvailable: true,
    timings: '5:30 AM - 10:00 PM Regular Schedule',
  },
  {
    id: 'fac-11',
    order: 11,
    title: 'Agriculture',
    icon: 'fa-solid fa-wheat-awn',
    category: 'Farming',
    description: 'Krishi Seva Kendra with soil testing laboratory, organic fertilizer distribution, and tractor hiring bank.',
    details: 'Crop weather advisory, PM Kisan Samman Nidhi facilitation desk, and drip irrigation subsidies.',
    isAvailable: true,
    timings: '8:00 AM - 6:00 PM',
  },
  {
    id: 'fac-12',
    order: 12,
    title: 'Banking',
    icon: 'fa-solid fa-piggy-bank',
    category: 'Finance',
    description: 'Customer Service Point (CSP) bank branch, cooperative society, and 24/7 solar micro-ATM cash facility.',
    details: 'Direct benefit transfer (DBT) disbursement, micro-credit for women self-help groups, and crop insurance.',
    isAvailable: true,
    timings: 'Banking: 10 AM - 4 PM / ATM: 24/7',
  },
  {
    id: 'fac-13',
    order: 13,
    title: 'Post Office',
    icon: 'fa-solid fa-envelope',
    category: 'Communication',
    description: 'India Post Branch with India Post Payments Bank (IPPB), speed post, parcel bookings, and postal life insurance.',
    details: 'Aadhaar-enabled payment system (AePS) doorstep cash withdrawal for senior citizens.',
    isAvailable: true,
    timings: '9:00 AM - 2:00 PM',
  },
  {
    id: 'fac-14',
    order: 14,
    title: 'Community Center',
    icon: 'fa-solid fa-people-roof',
    category: 'Civic',
    description: 'Spacious multipurpose community banquet hall for village weddings, social functions, and craft workshops.',
    details: 'Capacity of 600 people with solar sound system, community kitchen, and green lawns.',
    isAvailable: true,
    timings: 'Booking upon Gram Panchayat Approval',
  },
  {
    id: 'fac-15',
    order: 15,
    title: 'Sports Ground',
    icon: 'fa-solid fa-volleyball',
    category: 'Recreation',
    description: 'Lush green village sports stadium with running track, cricket pitch, volleyball court, and open-air gymnasium.',
    details: 'Youth physical training academy, daily morning yoga pavilion, and annual sports tournaments.',
    isAvailable: true,
    timings: '5:00 AM - 8:00 PM (Floodlights available)',
  },
  {
    id: 'fac-16',
    order: 16,
    title: 'Street Lights',
    icon: 'fa-solid fa-lightbulb',
    category: 'Infrastructure',
    description: '280 automated dusk-to-dawn solar LED street poles lighting up all village lanes, crossroads, and entry gates.',
    details: 'Central smart monitoring with battery backup to ensure total women and elder safety at night.',
    isAvailable: true,
    timings: 'Dusk to Dawn (6:00 PM - 6:00 AM Auto)',
  },
];

export const initialProjects = [
  {
    id: 'proj-1',
    title: 'Road Development',
    code: 'PMGSY-Phase 3',
    description: 'Widening of remaining 4 km feeder pathways into interlocking paver blocks with underground drainage network.',
    status: 'In Progress',
    progress: 82,
    budget: '₹34 Lakhs',
    completionDate: 'December 2026',
    beneficiaries: 'North & East Hamlet Residents (1,400+ citizens)',
    icon: 'fa-solid fa-road',
  },
  {
    id: 'proj-2',
    title: 'Solar Street Lights',
    code: 'Green-Energy-Mission',
    description: 'Deployment of 120 additional high-lumen solar LED street lamps along agricultural perimeter paths and temple corridors.',
    status: 'Completed',
    progress: 100,
    budget: '₹14 Lakhs',
    completionDate: 'August 2026',
    beneficiaries: 'Entire Village Population & Night Travelers',
    icon: 'fa-solid fa-solar-panel',
  },
  {
    id: 'proj-3',
    title: 'Clean Water Project',
    code: 'Jal Jeevan Mission',
    description: 'Installation of high-capacity automated RO filtration plant and secondary overhead reservoir with water meter telemetry.',
    status: 'Completed',
    progress: 100,
    budget: '₹48 Lakhs',
    completionDate: 'May 2026',
    beneficiaries: '1,180 Households (100% Coverage)',
    icon: 'fa-solid fa-faucet-drip',
  },
  {
    id: 'proj-4',
    title: 'School Development',
    code: 'Samagra Shiksha Abhiyan',
    description: 'Constructing modern interactive robotics laboratory, digital tablet desks, and separate sanitary complexes for girls.',
    status: 'In Progress',
    progress: 68,
    budget: '₹22 Lakhs',
    completionDate: 'January 2027',
    beneficiaries: '650+ Village School Students',
    icon: 'fa-solid fa-school',
  },
  {
    id: 'proj-5',
    title: 'Village Park',
    code: 'Amrit Sarovar Eco-Initiative',
    description: 'Eco-restoration of the sacred central pond into a landscaped Amrit Sarovar park with walking tracks, lotus pond, and native trees.',
    status: 'In Progress',
    progress: 90,
    budget: '₹18 Lakhs',
    completionDate: 'November 2026',
    beneficiaries: 'All Senior Citizens, Children & Families',
    icon: 'fa-solid fa-tree',
  },
  {
    id: 'proj-6',
    title: 'Digital Village Project',
    code: 'Digital India Gram',
    description: 'Setting up high-speed Common Service Center (CSC), village biometric kiosk, tele-doctor booth, and citizen mobile app portal.',
    status: 'Completed',
    progress: 100,
    budget: '₹26 Lakhs',
    completionDate: 'June 2026',
    beneficiaries: '100% Farmers, Women, Students & Businesses',
    icon: 'fa-solid fa-network-wired',
  },
];

export const initialCulture = [
  {
    name: 'Holi',
    hindiName: 'होली महापर्व',
    icon: 'fa-solid fa-palette',
    date: 'Phalguna Purnima (Spring)',
    description:
      'Celebrated with organic herbal gulal made from village marigolds and palash flowers. The community gathers at the village square for folk singing (Chaiti & Phagua) and sweets distribution.',
  },
  {
    name: 'Diwali',
    hindiName: 'दीपावली दीपोत्सव',
    icon: 'fa-solid fa-fire',
    date: 'Kartika Amavasya (Autumn)',
    description:
      'Over 20,000 earthen clay diyas handcrafted by local potters illuminate every courtyard, pond bank, and farm bund. Prayers are offered for agrarian prosperity and wealth.',
  },
  {
    name: 'Chhath Puja',
    hindiName: 'छठ महापर्व',
    icon: 'fa-solid fa-sun',
    date: 'Kartika Shukla Shashthi',
    description:
      'The sacred Vedic festival worshipping Surya Dev and Chhathi Maiya. Thousands gather at the cleaned village river ghats for evening and dawn arghya with bamboo soop and prasad.',
  },
  {
    name: 'Independence Day',
    hindiName: 'स्वतंत्रता दिवस (15 अगस्त)',
    icon: 'fa-solid fa-flag',
    date: '15th August Annual',
    description:
      'Solemn flag hoisting at Panchayat Bhawan followed by patriotic parades by school children, tribute to village army veterans, and distribution of laddu sweets.',
  },
  {
    name: 'Republic Day',
    hindiName: 'गणतंत्र दिवस (26 जनवरी)',
    icon: 'fa-solid fa-scale-balanced',
    date: '26th January Annual',
    description:
      'Annual Special Gram Sabha where the entire village discusses budget allocations, honors top student achievers, and pledges allegiance to constitutional democratic values.',
  },
  {
    name: 'Local Village Festival',
    hindiName: 'ग्राम देवी मेला एवं किसान महोत्सव',
    icon: 'fa-solid fa-drum',
    date: 'Margashirsha Shukla Dashami',
    description:
      'Our vibrant 3-day annual Gram Devi Mela featuring traditional wrestling (Dangal), agricultural innovation showcases, folk dance drama (Nautanki), and pottery fairs.',
  },
];

export const initialEvents = [
  {
    id: 'evt-1',
    title: 'Annual Gram Sabha & Development Review',
    date: '2026-11-20T10:00:00',
    displayDate: 'November 20, 2026 • 10:00 AM',
    location: 'Gram Panchayat Bhawan Main Hall',
    description: 'Open public assembly chaired by Mukhiya Ji to review solar project audits, water allocation, and sanction new farm loan subsidies.',
    organizer: 'Gram Panchayat Secretariat',
    category: 'Governance',
    icon: 'fa-solid fa-users-gear',
  },
  {
    id: 'evt-2',
    title: 'Free Mega Health & Eye Screening Camp',
    date: '2026-11-28T09:00:00',
    displayDate: 'November 28, 2026 • 09:00 AM',
    location: 'Primary Health Centre & School Ground',
    description: 'Specialist doctors from Varanasi Medical College offering free cataract diagnosis, diabetes tests, ECG, and free spectacles distribution.',
    organizer: 'Health Committee & Red Cross',
    category: 'Healthcare',
    icon: 'fa-solid fa-stethoscope',
  },
  {
    id: 'evt-3',
    title: 'Organic Farming & Drone Spray Workshop',
    date: '2026-12-05T11:00:00',
    displayDate: 'December 05, 2026 • 11:00 AM',
    location: 'Krishi Seva Kendra & Community Field',
    description: 'Live demonstration of agricultural drone spraying, bio-composting techniques, and PM Kisan credit card enrollment for all farmers.',
    organizer: 'Agriculture Advisory Board',
    category: 'Agriculture',
    icon: 'fa-solid fa-seedling',
  },
  {
    id: 'evt-4',
    title: 'Inter-Village Youth Cricket & Kabaddi Tournament',
    date: '2026-12-18T08:30:00',
    displayDate: 'December 18, 2026 • 08:30 AM',
    location: 'Sundarpur Stadium Ground',
    description: '16 neighboring village teams competing for the annual Gram Gaurav Trophy with cash awards, certificates, and cultural dinner.',
    organizer: 'Sundarpur Youth Sports Club',
    category: 'Sports',
    icon: 'fa-solid fa-trophy',
  },
];

// 20 photo items across categories
export const initialGallery = [
  // Nature (5)
  {
    id: 'gal-1',
    title: 'Golden Sunset over Wheat Fields',
    category: 'Nature',
    caption: 'Lush golden wheat fields waving gently under the calm dusk horizon of Sundarpur.',
    tags: ['Fields', 'Sunset', 'Golden Hour'],
    color: '#3d6c42',
    icon: 'fa-solid fa-wheat-awn',
  },
  {
    id: 'gal-2',
    title: 'Centuries-Old Sacred Banyan Tree',
    category: 'Nature',
    caption: 'The ancient banyan tree at the village entrance, providing shelter to generations.',
    tags: ['Banyan', 'Heritage', 'Nature'],
    color: '#2d5a27',
    icon: 'fa-solid fa-tree',
  },
  {
    id: 'gal-3',
    title: 'Restored Lotus Pond (Amrit Sarovar)',
    category: 'Nature',
    caption: 'Crystal-clear waters of the restored Amrit Sarovar with blooming pink lotus flowers.',
    tags: ['Water', 'Sarovar', 'Lotus'],
    color: '#1e6f5c',
    icon: 'fa-solid fa-water',
  },
  {
    id: 'gal-4',
    title: 'Morning Mist along River Stream',
    category: 'Nature',
    caption: 'Gentle silver mist rising from the village tributary as cattle graze peacefully.',
    tags: ['River', 'Morning', 'Peace'],
    color: '#467258',
    icon: 'fa-solid fa-cloud-sun',
  },
  {
    id: 'gal-5',
    title: 'Organic Vegetable Fields in Bloom',
    category: 'Nature',
    caption: 'Eco-friendly pesticide-free vegetable cultivation powered by drip irrigation.',
    tags: ['Organic', 'Farming', 'Greens'],
    color: '#285e33',
    icon: 'fa-solid fa-seedling',
  },

  // People (5)
  {
    id: 'gal-6',
    title: 'Village Elders at Chaupal',
    category: 'People',
    caption: 'Elders sharing timeless folk wisdom and discussing village progress under the neem tree.',
    tags: ['Elders', 'Chaupal', 'Heritage'],
    color: '#65532f',
    icon: 'fa-solid fa-users',
  },
  {
    id: 'gal-7',
    title: 'Empowered Women Self-Help Group',
    category: 'People',
    caption: 'Saraswati Mahila Samiti members packaging pure organic turmeric and honey.',
    tags: ['Women', 'Empowerment', 'SHG'],
    color: '#8b4513',
    icon: 'fa-solid fa-handshake-angle',
  },
  {
    id: 'gal-8',
    title: 'Children in Digital Smart Classroom',
    category: 'People',
    caption: 'Enthusiastic primary students learning interactive science on digital smartboards.',
    tags: ['Children', 'Education', 'Future'],
    color: '#2c5282',
    icon: 'fa-solid fa-graduation-cap',
  },
  {
    id: 'gal-9',
    title: 'Artisan Potter at his Traditional Wheel',
    category: 'People',
    caption: 'Master potter shaping natural terracotta diyas and water pots with rhythmic precision.',
    tags: ['Artisan', 'Craft', 'Pottery'],
    color: '#7b341e',
    icon: 'fa-solid fa-hands',
  },
  {
    id: 'gal-10',
    title: 'Farmer Celebrating Bumper Harvest',
    category: 'People',
    caption: 'A proud farmer holding fresh stalks of organic paddy grain in the morning sun.',
    tags: ['Farmer', 'Harvest', 'Pride'],
    color: '#4a5568',
    icon: 'fa-solid fa-person-digging',
  },

  // Festivals (5)
  {
    id: 'gal-11',
    title: 'Grand Diwali Diya Illumination',
    category: 'Festivals',
    caption: 'The village stepwell and streets sparkling with thousands of warm clay lamps.',
    tags: ['Diwali', 'Lights', 'Celebration'],
    color: '#b7791f',
    icon: 'fa-solid fa-fire',
  },
  {
    id: 'gal-12',
    title: 'Vibrant Holi Colors of Joy',
    category: 'Festivals',
    caption: 'Villagers united in playful celebration with herbal colors and folk music.',
    tags: ['Holi', 'Colors', 'Harmony'],
    color: '#9f1239',
    icon: 'fa-solid fa-palette',
  },
  {
    id: 'gal-13',
    title: 'Chhath Puja Sunrise at the Ghat',
    category: 'Festivals',
    caption: 'Devotees offering prayers to the rising sun amidst holy chants and sacred lamps.',
    tags: ['Chhath', 'Sun', 'Devotion'],
    color: '#c05621',
    icon: 'fa-solid fa-sun',
  },
  {
    id: 'gal-14',
    title: 'Independence Day Flag Hoisting',
    category: 'Festivals',
    caption: 'Tricolor flag proudly fluttering at Panchayat Bhawan with school children singing.',
    tags: ['Tricolor', 'Patriotism', 'National'],
    color: '#276749',
    icon: 'fa-solid fa-flag',
  },
  {
    id: 'gal-15',
    title: 'Gram Devi Mela Cattle Fair',
    category: 'Festivals',
    caption: 'Colorful festive stalls, traditional sweet shops, and lively cattle shows at the annual fair.',
    tags: ['Fair', 'Mela', 'Tradition'],
    color: '#742a2a',
    icon: 'fa-solid fa-tent',
  },

  // Development (5)
  {
    id: 'gal-16',
    title: 'Solar Powered Street Lighting Grid',
    category: 'Development',
    caption: 'Modern solar street lights illuminating village thoroughfares and village entry gate.',
    tags: ['Solar', 'Green Energy', 'Smart Village'],
    color: '#234e52',
    icon: 'fa-solid fa-solar-panel',
  },
  {
    id: 'gal-17',
    title: 'Newly Paved PMGSY Concrete Roadway',
    category: 'Development',
    caption: 'Clean, wide paved concrete road with side drains connecting every hamlet to the highway.',
    tags: ['Roads', 'Infrastructure', 'Connectivity'],
    color: '#2d3748',
    icon: 'fa-solid fa-road',
  },
  {
    id: 'gal-18',
    title: 'Central Jal Jeevan RO Filtration Plant',
    category: 'Development',
    caption: 'State-of-the-art community water purification plant delivering clean water to all.',
    tags: ['Water', 'Health', 'Purity'],
    color: '#2b6cb0',
    icon: 'fa-solid fa-faucet-drip',
  },
  {
    id: 'gal-19',
    title: 'High-Tech Common Service Center (CSC)',
    category: 'Development',
    caption: 'Villagers accessing direct online government portals, pension registries, and telemedicine.',
    tags: ['Digital', 'E-Governance', 'CSC'],
    color: '#319795',
    icon: 'fa-solid fa-laptop',
  },
  {
    id: 'gal-20',
    title: 'Village Youth Sports Ground & Gym',
    category: 'Development',
    caption: 'Modern outdoor fitness gym and well-maintained cricket & athletic running tracks.',
    tags: ['Sports', 'Youth', 'Fitness'],
    color: '#38a169',
    icon: 'fa-solid fa-dumbbell',
  },
];

export const initialPlaces = [
  {
    id: 'plc-1',
    name: 'Village Primary & Higher Secondary School',
    icon: 'fa-solid fa-school',
    category: 'Education',
    location: 'North Campus, Shanti Marg',
    timings: '07:30 AM - 02:30 PM',
    description: 'Government model composite school offering smart classes from Grade 1 to 12, well-stocked library, and sports training.',
  },
  {
    id: 'plc-2',
    name: 'Primary Health Centre (PHC)',
    icon: 'fa-solid fa-hospital',
    category: 'Healthcare',
    location: 'Hospital Road, Near Block Boundary',
    timings: 'Open 24/7 (Emergency & Maternity)',
    description: 'Modern 10-bed rural hospital with medical officers, delivery suite, pathology laboratory, and oxygen concentrators.',
  },
  {
    id: 'plc-3',
    name: 'Ancient Shri Someshwar Mahadev Temple',
    icon: 'fa-solid fa-place-of-worship',
    category: 'Heritage',
    location: 'Temple Ghat, Old Village Center',
    timings: '05:00 AM - 12:00 PM & 04:30 PM - 09:00 PM',
    description: 'Historical 18th-century stone temple known for spiritual serenity, annual Shivratri mela, and shaded banyan pavilion.',
  },
  {
    id: 'plc-4',
    name: 'Gram Panchayat Bhawan & Secretariat',
    icon: 'fa-solid fa-building-columns',
    category: 'Governance',
    location: 'Ward No. 04, Central Square',
    timings: '10:00 AM - 05:00 PM (Monday - Saturday)',
    description: 'The administrative nucleus hosting the Sarpanch office, meeting conference hall, BharatNet server room, and citizen desks.',
  },
  {
    id: 'plc-5',
    name: 'Local Haat Bazaar & Kisan Mandi',
    icon: 'fa-solid fa-shop',
    category: 'Commerce',
    location: 'Market Road, Near Main Chauraha',
    timings: 'Morning: 06:30 AM - 01:00 PM | Evening: 04:00 PM - 09:00 PM',
    description: 'Centrally planned daily market with 50+ sheds for fresh agricultural harvest, groceries, tailoring, and village tea stalls.',
  },
  {
    id: 'plc-6',
    name: 'Sundarpur Main Bus & E-Rickshaw Terminal',
    icon: 'fa-solid fa-bus-simple',
    category: 'Transport',
    location: 'Highway Junction, Village Gate',
    timings: '05:30 AM - 10:00 PM Daily',
    description: 'Clean passenger shelter with digital timetable display, drinking water fountain, and direct transit to Varanasi railway station.',
  },
];

export const initialHeroes = [
  {
    id: 'hero-1',
    name: 'Shri Rameshwar Sharma',
    role: 'Dedicated Teacher',
    experience: '35+ Years in Service',
    description: 'Taught mathematics and values to three generations of villagers. Founded the free evening coaching center for underprivileged girls.',
    icon: 'fa-solid fa-chalkboard-user',
    color: '#2e7d32',
  },
  {
    id: 'hero-2',
    name: 'Dr. Sunita Patel (MBBS)',
    role: 'Rural Medical Officer',
    experience: '12 Years at PHC',
    description: 'Spearheaded zero maternal mortality record in the village, 100% infant immunization coverage, and round-the-clock emergency medical attention.',
    icon: 'fa-solid fa-user-doctor',
    color: '#0277bd',
  },
  {
    id: 'hero-3',
    name: 'Kisan Ramdayal Singh',
    role: 'Organic Farming Pioneer',
    experience: 'Krishi Ratna Awardee',
    description: 'Convinced 300+ village farmers to abandon synthetic chemicals in favor of vermicompost, zero-budget farming, and drip micro-irrigation.',
    icon: 'fa-solid fa-tractor',
    color: '#558b2f',
  },
  {
    id: 'hero-4',
    name: 'Smt. Ananya Devi',
    role: 'Social Worker & SHG Leader',
    experience: 'President, Mahila Samiti',
    description: 'Empowered over 400 rural women through micro-savings, sewing centers, solar lamp assembly units, and financial literacy workshops.',
    icon: 'fa-solid fa-handshake-angle',
    color: '#ad1457',
  },
  {
    id: 'hero-5',
    name: 'Mukhiya Rajesh Kumar Verma',
    role: 'Visionary Village Leader',
    experience: 'Two-term Sarpanch',
    description: 'Pioneered transparent digital Gram Panchayat meetings, 100% solar conversion, Har Ghar Jal tap lines, and state model village recognition.',
    icon: 'fa-solid fa-award',
    color: '#e65100',
  },
];

export const initialNews = [
  {
    id: 'news-1',
    title: 'Sundarpur Awarded "Best Digital Panchayat" of the Year',
    category: 'Village News',
    date: 'October 04, 2026',
    summary: 'The Ministry of Panchayati Raj awarded Sundarpur the prestigious Rashtriya Gaurav Gram Sabha award for 100% digital governance.',
    details: 'The award includes a development grant of ₹50 Lakhs earmarked for a new digital community library and agricultural cold storage unit.',
    isPinned: true,
  },
  {
    id: 'news-2',
    title: 'Special PM-Kisan 17th Installment Verification Camp at CSC',
    category: 'Government Schemes',
    date: 'September 28, 2026',
    summary: 'All eligible small and marginal farmers can complete biometric e-KYC and bank Aadhaar-linking at zero cost this week.',
    details: 'Please bring original Aadhaar Card, land revenue record (Khatauni), and bank passbook to counter no. 2 at Panchayat Bhawan.',
    isPinned: false,
  },
  {
    id: 'news-3',
    title: 'Completion of 120 Solar Street Lamps in Outer Hamlet Sectors',
    category: 'Development Updates',
    date: 'September 15, 2026',
    summary: 'Gram Panchayat confirms all 120 smart solar LED poles are now fully operational with dusk-to-dawn sensors.',
    details: 'The initiative has cut village electricity expenses by 42% while significantly improving night-time safety for women and farmers.',
    isPinned: false,
  },
  {
    id: 'news-4',
    title: 'Announcement: Free Veterinary Health Camp for Livestock',
    category: 'Announcements',
    date: 'September 10, 2026',
    summary: 'Senior veterinary surgeons will provide free deworming, foot-and-mouth vaccination, and nutritional mineral supplements for cattle.',
    details: 'Farmers are requested to bring their cattle and goats to the Old Haat grounds on Sunday from 8:00 AM to 1:00 PM.',
    isPinned: false,
  },
];

export const initialContacts = [
  {
    id: 'cnt-1',
    name: 'Sunil Pandey',
    email: 'sunil.p@gmail.com',
    phone: '+91 98711 22334',
    subject: 'Request for Paver Block repair near North Pond',
    message: 'The recent monsoon rains caused slight settlement on the culvert approach near Ward 3. Please arrange sand leveling.',
    status: 'Reviewed',
    createdAt: '2026-09-20T10:15:00.000Z',
  },
];

export const initialSuggestions = [
  {
    id: 'sug-1',
    name: 'Pooja Tiwari',
    email: 'pooja.t@outlook.com',
    phone: '+91 98222 33445',
    category: 'Village Development',
    message: 'Can we set up a dedicated digital study room in the Panchayat Bhawan with high-speed Wi-Fi for youth preparing for competitive exams?',
    upvotes: 42,
    status: 'Approved',
    createdAt: '2026-09-18T14:30:00.000Z',
  },
];
